# action.yml
name: 'Split Monorepo'
description: 'Split the directories in a monorepo up into separate per-project repos'
# inputs:
#   name:
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  #args:
    #- "${{ inputs.who-to-greet }}"
